### ISSUE TITLE
`stateVersion` mismatch

### ISSUE THREAD

**Issue by juangiordana** [juspay/nixos-unified-template#111]
```nix
# configurations/nixos/example/configuration.nix
system.stateVersion = "24.05";

# configurations/home/runner.nix
home.stateVersion = "22.11"; # should be "24.05"
```

https://github.com/juspay/nixos-unified-template/blob/ceda317722dcb78239826fbeab7cfe818889a12c/configurations/home/runner.nix#L12

**Comment by srid** [comment]
https://github.com/juspay/nixos-unified-template/pull/117
