### ISSUE TITLE
Make sure that shell completions work

### ISSUE THREAD

**Issue by srid** [juspay/nixos-unified-template#25]
On macOS in particular zsh completions should work. Do they?

For nix-darwin, it requires extra configuration: https://github.com/srid/nixos-config/pull/50 

cf. https://github.com/nix-community/home-manager/issues/2562

**Comment by shivaraj-bh** [comment]
Works for me on macOS. I am on latest home-manager.

```nix
{
  zsh = {
    enable = true;
    enableAutosuggestions = true;
  };
}
```

This option has now been renamed to `zsh.autosuggestion.enable = true;`

**Comment by srid** [comment]
Wait, this issue is about auto*completion*, but you are talking about auto*suggestion*. What is the connection?

https://github.com/zsh-users/zsh-autosuggestions?tab=readme-ov-file

**Comment by shivaraj-bh** [comment]
> Wait, this issue is about autocompletion, but you are talking about autosuggestion. What is the connection?

Right, my bad

**Comment by srid** [comment]
I think @rsrohitsingh682 confirmed this to work on macOS (sans nix-darwin)?
