### ISSUE TITLE
Make `nix-direnv.package` in home-manager override Nix

### ISSUE THREAD

**Issue by srid** [juspay/nixos-unified-template#68]
## Current

https://github.com/nix-community/home-manager/blob/c2cd2a52e02f1dfa1c88f95abeb89298d46023be/modules/programs/direnv.nix#L95

## Expected

Override nix package like nixos module does:

https://github.com/NixOS/nixpkgs/blob/6a9d18e057c1dbd6acefa6fe094de8f3c68051a2/nixos/modules/programs/direnv.nix#L64

## Context

The reverted PR: https://github.com/juspay/nix-dev-home/pull/66

**Comment by srid** [comment]
Until then,

<img width="486" alt="image" src="https://github.com/user-attachments/assets/296413be-03dd-4dae-bffa-7220ff4250d1">

**Comment by shivaraj-bh** [comment]
https://github.com/nix-community/home-manager/pull/5773 resolves this issue

**Comment by srid** [comment]
@shivaraj-bh Can we get that PR merged by asking someone upstream?

**Comment by srid** [comment]
Not sure if even need this.
