### ISSUE TITLE
Add tmate as a `program`

### ISSUE THREAD

**Issue by srid** [juspay/nixos-unified-template#98]
Instead of:

<img width="274" alt="image" src="https://github.com/user-attachments/assets/4790dff7-3adf-42f7-9326-65b7f960971d">

use `programs.tmate.*`:

https://github.com/nix-community/home-manager/blob/64c6325b28ebd708653dd41d88f306023f296184/modules/programs/tmate.nix#L13

Also, add `programs.tmux`.

**Comment by inithinx** [comment]
Consider adding [tmux](https://home-manager-options.extranix.com/?query=tmux&release=release-24.11) and integrating it with nixvim with [vim-tmux-navigator](https://nix-community.github.io/nixvim/plugins/tmux-navigator/index.html)
